name: "e2e"
on: [push]
jobs:
  test-e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest # set to either ubuntu-latest (for Linux) or windows-latest (for windows)
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '24' #found by running node v in terminal
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run your tests as virtual headed browser
        run: xvfb-run npx playwright test tests/home.spec.ts    
      # - name: Run your tests
      #   run: npx playwright test tests/home.spec.ts
      - name: Upload test Results
        if:  always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: test-results 